### ISSUE TITLE
Feature request: multiple calibrations in one cycle.

### ISSUE THREAD

**Issue by alimhassam** [xdrip-js/Logger#121]
One feature/improvement needed to Logger is the ability to send multiple calibrations in one wake up cycle.  This avoids waiting 10 minutes on initial sensor calibrations.

Also when something fails in the logger loop, on the cycle where the calibration was supposed to be sent, then we currently need to do another blood finger prick. Instead, we should allow slightly backdated calibrations. I think up to 20-30 minutes seems reasonable.

**Comment by tynbendad** [comment]
backdated calibrations might work best if we went back and matched them up with the tx values of the same time.

**Comment by efidoman** [comment]
This works in the latest Logger dev now. I'll leave the issue open until a few more people update and verify.

**Comment by efidoman** [comment]
My additional tests show that the 2 calibrations are accepted by the transmitter in a single wake-up cycle. For restarts it does skip the warmup and first calibration, but not the second calibration. This may be a tx limitation ... not sure.

**Comment by efidoman** [comment]
Once NS has a restart Treatment type (PR is in progress) then we can update Logger to check if restart was done in last (say) 1 hour and then issue a "2nd calibration" automatically in the next cycle if the state is still "2nd Calibration".

**Comment by efidoman** [comment]
Feature completed with the exception of the restart scenario for some transmitter tests.
