### ISSUE TITLE
Please remove dependency on $HOME/myopenaps/pump.ini

### ISSUE THREAD

**Issue by PieterGit** [xdrip-js/Logger#137]
With 0.7.0-dev and PR https://github.com/openaps/oref0/pull/1176 there is no need for oref0 to create a pump.ini. Currently oref0 must create it because xdripjs-js Logger uses it for the fakemeter, see https://github.com/xdrip-js/Logger/blob/f7228485c7a66300f280ac789b5dce0252ffa279/xdrip-get-entries.sh#L245
Can the Logger code be altered to comply with the 0.7.x oref0 way of doing it to read these settings from the preferences.json?

See @cluckj review at https://github.com/openaps/oref0/pull/1176#pullrequestreview-205854470 for details.

**Comment by efidoman** [comment]
Yes, thanks for posting. I will work on this issue next.

**Comment by efidoman** [comment]
I remembered that having this variable set is no longer necessary for fakemeter, so I tested Logger with that line deleted and fakemeter works fine. In addition, the fakemeter processing has moved in the latest Logger and OpenAPS dev to process as part of the OpenAPS loop. I'll check in the Logger code now.

**Comment by efidoman** [comment]
Done. 
pump.ini can be removed from OpenAPS now.
