### ISSUE TITLE
Rebooting in 15 seconds to fix BT and xdrip-js

### ISSUE THREAD

**Issue by bousbait** [xdrip-js/Logger#155]
after activating Logger and BT tethering, I received the following error and the PI will restart. it happened several times a day! 
"Broadcast message from root@dorrarig1 (somewhere) (Tue May 28 03:31:34 2019):
Rebooting in 15 seconds to fix BT and xdrip-js - save your work quickly!"

any idea?

**Comment by tynbendad** [comment]
logger reboots the rig if it is active but not able to read.  there was a recent change going in to put a preference in to disable this, i don't recall if it made it in but probably in dev branch.

**Comment by efidoman** [comment]
Yep, that preference is there now. Set watchdog to false to disable the reboots.

{
  "transmitter_id": "8XXXXX",
  "sensor_code": "9XXX",
  "mode": "not-expired",
  "pump_units": "mg/dl",
  "alternate_bluetooth_channel": true,
  "watchdog": false,
  "fake_meter_id": "000000",
  "fakemeter_only_offline": false
}
