### ISSUE TITLE
bad internet connection causes missed readings

### ISSUE THREAD

**Issue by tynbendad** [xdrip-js/Logger#194]
my router has been having some issues lately causing us to lose internet overnight for a few hours. i noticed that after the internet is back, logger uploads spotty info to nightscout. looking into it a bit more there were actual missed readings, and the cause is due to incorrectly timing the "Waiting " in check_last_glucose_time_smart_sleep().

the code in that function uses the modification time of the file last-entry.json, however that file is modified after post-nightscout-with-backfill() call in main(), and I assume when internet connection drops that function has a long timeout (the curl's appear to use -m 30, and there are up to 3 of them, which would delay the next start by 90 seconds if all timeout).

the fix would be simple, just move the cp before the call to post-nightscout-with-backfill(), however there is another cp to last-entry.json at the end of capture_entry_values() and i'm not sure how this affects the modification timestamp.

also tacking on an unrelated issue here, from gitter, just to make sure we don't miss it:
@efidoman >A simpler solution may be to just add tx-expired to every status where tx age > 90. Is 90 days the same expire time frame for g5 and g6?

fidoman @efidoman Aug 11 04:22
Yes, I confirmed via Dexcom's web site, both are 90 days.
https://www.dexcom.com/faq/how-long-does-dexcom-g6-transmitter-last?category=2641

**Comment by tynbendad** [comment]
i think the cp to last-entry.json at the end of capture_entry_values() happens after the time check and before the other cp, so swapping the order of the one currently after post-nightscout-with-backfill() should fix this - am trying it locally. (it could also be that one of the cp's is redundant, but i haven't looked at that).

**Comment by tynbendad** [comment]
probably just changing both "cp"'s to "cp -p"'s would fix this as well, and the wait time should be more accurate.

**Comment by efidoman** [comment]
Good catch and nice write-up. I think that "cp -p" is the most straightforward way to resolve this issue. I will resolve both of these issues in the branch I'm doing now that will also add support for the new g6 firmware.

**Comment by efidoman** [comment]
Looking at this some more .... it's probably better to create a new file just for timing vs. using the last-entry.json timestamp. That file gets changed more than twice during Logger's loop. I'll implement a new file just for timing of the loop.

**Comment by efidoman** [comment]
Ah - there is already a timestamp file that is touched when a valid entry.json file is created. last-watchdog ... I'm using that one. BTW - the PR is here if you want to take a look at the diff.

https://github.com/xdrip-js/Logger/pull/195/files

**Comment by efidoman** [comment]
Both issues should be resolved in Logger dev branch now. I'll leave this one open until someone in addition to my testing confirms.
