### ISSUE TITLE
alternate bt channel should be automatically picked when configuring logger

### ISSUE THREAD

**Issue by zasteph** [xdrip-js/Logger#210]
After running the oref0-setup.sh, the "cgm-transmitter" command creates the ~/myopenaps/xdripjs.json config file needed by the logger; however, the logger is supposed to work in "parallel" with the main G5/G6 user (phone?). 
The json file created by the "cgm-transmitter" command does not set the "alternate_bluetooth_channel" as true.

**Comment by scottleibrand** [comment]
If we decide not to do this in Logger itself, I'd also be happy to do it within oref0-setup.

**Comment by efidoman** [comment]
PR created for Logger - https://github.com/xdrip-js/Logger/pull/226

**Comment by efidoman** [comment]
PR's merged. Now Logger defaults to true for alternate_bluetooth_channel
