### ISSUE TITLE
Are there any plans to support Ambrosia Systems Blucon / Nightrider ?

### ISSUE THREAD

**Issue by bustavo** [xdrip-js/Logger#55]

**Comment by efidoman** [comment]
I'm not sure what you mean? Are you asking about the dexcom g5 or about another system like Libre sensor? We would need a different base library to communicate with the Libre. Someone would need to write an equivalent xdrip-js repository I think.

**Comment by bustavo** [comment]
Hi, @efidoman I am talking about the Ambrosia Systems Blucon ( http://ambrosiasys.com ) it is supported by xdrip, but I did not find the functionality on this version of xdrip...

Right now I am trying to read the data from the Blucon using python ( pygatt ) but am still having trouble decoding the data from the device...

**Comment by efidoman** [comment]
Yes, if you can get something like pygatt working to handle all the bluetooth communications to the blucon then we might be able to consider an enhancement to add it as a source for bg to Logger. Good luck with the BLE comms, that can be really tough. Look at what xdrip+ did and maybe that'll help some. 

On another project, I'm working with ecc1's BLE go library that is based on godbus. It's hard no matter what technology you use to figure out undocumented BLE comms.

**Comment by efidoman** [comment]
Closing - Blucon / Nightrider support is not in scope for Logger

**Comment by janewhile** [comment]
Hi, Would like to share my experience with BluCon. I am using Abbott's FreeStyle Libre Sensor with Ambrosia's NightRider BluCon with LinkBluCon app. Initially it was not connecting but when i emailed them then i came to know i was not entering the right passcode, later it connected. There was some reading issue also which was not matching with my glucometer, later came to know calibration is required every couple of days. Every thing has been working fine for last 8 months. Now i can see my reading on my Huawei 2 smart watch without phone. It's fantastic now. As comparative to Dexcom Ambrosia's device is much cost effective.
